basePath: /
host: localhost:8081
info:
  contact: {}
  title: Календарь
  version: "1.0"
paths:
  /session:
    post:
      consumes:
      - application/json
      responses: {}
  /users:
    post:
      consumes:
      - application/json
      responses: {}
swagger: "2.0"
